### ISSUE TITLE
[Bug]: App crashes because xdg-data/applications dir does not exist

### ISSUE THREAD

**Issue by yuntaz0** [fabrialberio/Pins#71]
### Describe the bug

The app crashes on a fresh install of Fedora 42 because `xdg-data/applications` does not exist.

### To Reproduce

1. A fresh install of Fedora KDE, or remove `xdg-data/applications` directory.
2. Open Pins and click the + icon at the top left corner.
3. The application crashes.

### Linux distribution

Fedora 42 KDE

### Additional context

Changing its Flatpak permission seems to fix the issue.
From`--filesystem=xdg-data/applications:rw` to  `--filesystem=xdg-data/applications:create`

**Comment by fabrialberio** [comment]
Thank you for your report!
I didn't do this previously because somewhere in the Flatpak guidelines it says that it is discouraged to add ":create" to "xdg-data" dirs in the manifest.
I can no longer find this, but to avoid issues I fixed it by creating the directory before trying to save a file there.

**Comment by yuntaz0** [comment]
Hi, I’ve updated the app to version 2.3.0 and can still reproduce this issue.

**Comment by fabrialberio** [comment]
Ok, I have found a new solution and tested it properly.
I will release version 2.3.1 with this fix.
